name: C/C++ CI

on: [push, pull_request, schedule]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: sudo apt-get install -y -f libgtk-3-dev libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev libappindicator3-dev
    - name: build
      run: bash build_linux.sh

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./build_windows.bat

  build-osx:
    runs-on: macos-latest
    steps:
    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install boost
      run: brew install boost@1.76
    - uses: actions/checkout@v1
    - name: build
      run: bash build_macos.sh

# ---- This step fails.  TODO: Fix and uncomment -------
#   build-freebsd:
#     runs-on: macos-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: build
#       uses: vmactions/freebsd-vm@v0.1.4
#       with:
#         usesh: true
#         prepare: pkg install -y gtk+-3.0 webkit2gtk-4.0 glib-2.0 appindicator3-0.1
#         run: sh build_freebsd.sh
