name: Create release zip
on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 

jobs:   
  create-release-zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Create Release zip
      uses: vimtor/action-zip@v1
      with: 
        files: ./bin/neutralino-linux_x64 ./bin/neutralino-win_x64.exe ./bin/neutralino-mac_x64 ./bin/WebView2Loader.dll
        dest: './bin/neutralinojs-v${{github.event.inputs.version}}.zip'
    - name: Add, Commit and Push Release Zip
      uses: EndBug/add-and-commit@v7.4.0
      with:
        default_author: github_actions
        message: 'Add pre-built x64 binaries to release zip' 
        add: './bin/neutralinojs*.zip'
    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.0
      with:
          custom_tag: v${{github.event.inputs.version}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Neutralinojs v${{github.event.inputs.version}} released!
          body: 'Test release'
