
name: Create release
on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 

jobs:

  build-darwin:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        export MACOSX_DEPLOYMENT_TARGET=11.0
        export CXX=clang++\ -ObjC++ 
        ./scripts/bz.py --target_arch x64
        ./scripts/bz.py --target_arch arm64
        lipo bin/neutralino-mac_x64 bin/neutralino-mac_arm64 -create -output bin/neutralino-mac_universal
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: darwin_binary
        path: |
          bin/neutralino-mac_x64
          bin/neutralino-mac_arm64
          bin/neutralino-mac_universal
        
  create-release:
    needs: [build-darwin]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Download Darwin build artifacts 
      uses: actions/download-artifact@v2
      with:
        name: darwin_binary
        path: ./bin
        
    - name: Create Release zip
      uses: vimtor/action-zip@v1
      with:
        files: ./bin/neutralino-mac_x64 ./bin/neutralino-mac_arm64 ./bin/neutralino-mac_universal
        dest: './bin/neutralinojs-v${{github.event.inputs.version}}.zip' 
        
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
          tag: v${{github.event.inputs.version}}
          name: Neutralinojs v${{github.event.inputs.version}} released!
          artifacts: './bin/neutralinojs-v${{github.event.inputs.version}}.zip'